/*
Copyright © 2018 Kyle Bai(kyle.b@inwinstack.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/inwinstack/pan-operator/pkg/apis/inwinstack/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNATPolicies implements NATPolicyInterface
type FakeNATPolicies struct {
	Fake *FakeInwinstackV1alpha1
	ns   string
}

var natpoliciesResource = schema.GroupVersionResource{Group: "inwinstack.com", Version: "v1alpha1", Resource: "natpolicies"}

var natpoliciesKind = schema.GroupVersionKind{Group: "inwinstack.com", Version: "v1alpha1", Kind: "NATPolicy"}

// Get takes name of the nATPolicy, and returns the corresponding nATPolicy object, and an error if there is any.
func (c *FakeNATPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.NATPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natpoliciesResource, c.ns, name), &v1alpha1.NATPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NATPolicy), err
}

// List takes label and field selectors, and returns the list of NATPolicies that match those selectors.
func (c *FakeNATPolicies) List(opts v1.ListOptions) (result *v1alpha1.NATPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natpoliciesResource, natpoliciesKind, c.ns, opts), &v1alpha1.NATPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NATPolicyList{ListMeta: obj.(*v1alpha1.NATPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.NATPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nATPolicies.
func (c *FakeNATPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natpoliciesResource, c.ns, opts))

}

// Create takes the representation of a nATPolicy and creates it.  Returns the server's representation of the nATPolicy, and an error, if there is any.
func (c *FakeNATPolicies) Create(nATPolicy *v1alpha1.NATPolicy) (result *v1alpha1.NATPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natpoliciesResource, c.ns, nATPolicy), &v1alpha1.NATPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NATPolicy), err
}

// Update takes the representation of a nATPolicy and updates it. Returns the server's representation of the nATPolicy, and an error, if there is any.
func (c *FakeNATPolicies) Update(nATPolicy *v1alpha1.NATPolicy) (result *v1alpha1.NATPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natpoliciesResource, c.ns, nATPolicy), &v1alpha1.NATPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NATPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNATPolicies) UpdateStatus(nATPolicy *v1alpha1.NATPolicy) (*v1alpha1.NATPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(natpoliciesResource, "status", c.ns, nATPolicy), &v1alpha1.NATPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NATPolicy), err
}

// Delete takes name of the nATPolicy and deletes it. Returns an error if one occurs.
func (c *FakeNATPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natpoliciesResource, c.ns, name), &v1alpha1.NATPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNATPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NATPolicyList{})
	return err
}

// Patch applies the patch and returns the patched nATPolicy.
func (c *FakeNATPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NATPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natpoliciesResource, c.ns, name, data, subresources...), &v1alpha1.NATPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NATPolicy), err
}
